# **Tipos de Matriz**

$$A=\begin{bmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31}& a_{32} & a_{33}
\end{bmatrix}$$

In [86]:
import numpy as np

# Definir la matriz
A = np.array([[2, 4, 6],
              [8, 10, 12],
              [14, 16, 18]])

#Se accede a un elemento específico usando A[i, j], recordando que Python indexa desde 0
# Elemento en la posición (1,3) (índices en Python comienzan desde 0)
elemento_A_1_3 = A[0, 2]


# Obtener las filas
fila_1 = A[0, :]
fila_2 = A[1, :]
fila_3 = A[2, :]

# Obtener las columnas
columna_1 = A[:, 0]
columna_2 = A[:, 1]
columna_3 = A[:, 2]

# Imprimir resultados
print(f"Matriz A:\n{A}\n")
print(f"Elemento A[1,3]: {elemento_A_1_3}\n")
print(f"Filas:")
print(f"Fila 1: {fila_1}")
print(f"Fila 2: {fila_2}")
print(f"Fila 3: {fila_3}\n")
print(f"Columnas:")
print(f"Columna 1: {columna_1}")
print(f"Columna 2: {columna_2}")
print(f"Columna 3: {columna_3}")


Matriz A:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Elemento A[1,3]: 6

Filas:
Fila 1: [2 4 6]
Fila 2: [ 8 10 12]
Fila 3: [14 16 18]

Columnas:
Columna 1: [ 2  8 14]
Columna 2: [ 4 10 16]
Columna 3: [ 6 12 18]


Matriz transpuesta


In [87]:
# Matriz transpuesta
transpuesta_A = A.T
print(transpuesta_A)

[[ 2  8 14]
 [ 4 10 16]
 [ 6 12 18]]


Tipos de matrices
$$I=\begin{bmatrix}
1 & 0 & 0 \\
0 & 1& 0 \\
0& 0 & 1
\end{bmatrix}$$

In [88]:
# Matriz Identidad (I)
I = np.eye(3)
# Imprimir resultados
print("Matriz Identidad (I):\n", I, "\n")


Matriz Identidad (I):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 



Matriz Cero
$$
0=\begin{bmatrix}
0 & 0 & 0 \\
0 & 0& 0 \\
0& 0 & 0
\end{bmatrix}
$$

In [89]:
# Matriz Cero (0)
O = np.zeros((3,3))
# Imprimir resultados
print("Matriz Cero (0):\n", O, "\n")

Matriz Cero (0):
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 



Matriz Diagonal (D)

$$
A=\begin{bmatrix}
a_{11} & 0 & 0 \\
0 & a_{22}& 0 \\
0& 0 & a_{33}
\end{bmatrix}
$$

In [90]:
# Matriz Diagonal (D)
D = np.diag([2, 5, 8])

# Imprimir resultados
print("Matriz Diagonal (D):\n", D)

Matriz Diagonal (D):
 [[2 0 0]
 [0 5 0]
 [0 0 8]]


In [91]:
# Definir la matriz diagonal
D = np.array([[2, 0, 0],
              [0, 5, 0],
              [0, 0, 8]])

# Extraer la diagonal
diagonal = np.diagonal(D)

# Mostrar la diagonal
print(diagonal)

[2 5 8]


Matriz superior

$$
A=\begin{bmatrix}
a_{11} & a_{12} & a_{13} \\
0 & a_{22}& a_{23} \\
0& 0 & a_{33}
\end{bmatrix}
$$

In [92]:
# Matriz triangular superior
T = np.array([[2, 3, 4],
              [0, 5, 6],
              [0, 0, 7]])
print("Matriz triangular superior:")
print(T)

Matriz triangular superior:
[[2 3 4]
 [0 5 6]
 [0 0 7]]


Matriz inferior


$$
A=\begin{bmatrix}
a_{11}& 0 & 0 \\
a_{21}& a_{22}& 0 \\
a_{31}&a_{32} & a_{33}
\end{bmatrix}
$$

In [93]:
# Matriz triangular inferior
L = np.array([[2, 0, 0],
              [3, 5, 0],
              [4, 6, 7]])
print("\nMatriz triangular inferior:")
print(L)


Matriz triangular inferior:
[[2 0 0]
 [3 5 0]
 [4 6 7]]


Matriz simetrica

$$
A=\begin{bmatrix}
1& 2 & 3\\
2& 5& 0 \\
3&0 & 5
\end{bmatrix}
$$

In [94]:
# Matriz simétrica
S = np.array([[2, 3, 4],
              [3, 5, 6],
              [4, 6, 8]])
print("\nMatriz simétrica:")
print(S)


Matriz simétrica:
[[2 3 4]
 [3 5 6]
 [4 6 8]]


asimétrica: Una matriz simétrica es una matriz cuadrada que es igual a su transpuesta. Es decir:

$$
A=A^{t}
$$

$$
A=\begin{bmatrix}
0& 2 & 1\\
-2& 0& 3 \\
-1&-3 & 0
\end{bmatrix}
$$

In [95]:
A = np.array([
    [1, 2, 3],
    [2, 4, 5],
    [3, 5, 6]
])

print(np.allclose(A, A.T))  # True → es simétrica

True


Asimétrica:
Una matriz asimétrica es una matriz que no es simétrica, es decir:
$$A\neq A^{t}$$

$$
A=\begin{bmatrix}
0& 2 & 1\\
-2& 0& 3 \\
-1&-3 & 0
\end{bmatrix}
$$

In [96]:
# Ejemplo de matriz NO simétrica (asimétrica en el sentido más común)
asimetrica = np.array([
    [1, 2, 3],
    [0, 4, 5],
    [3, 5, 6]
])

asimetrica_check = np.allclose(asimetrica, asimetrica.T)
asimetrica_check


False

Una matriz antisimétrica (también llamada matriz skew-symmetric) es una matriz cuadrada que cumple la siguiente propiedad fundamental:

$$A^{t}=-A$$

Es decir, la transpuesta de la matriz es igual a su opuesto.

In [115]:
import numpy as np

A = np.array([
    [0, 3, -2],
    [-3, 0, 4],
    [2, -4, 0]
])
print("Matriz A:")
print(A)

print("Transpuesta de A:")
print(A.T)

print("Negativa de A:")
print(-A)

print("¿A es antisimétrica?")
print(np.allclose(A.T, -A))   # True, np.allclose verifica si dos matrices son aproximadamente iguales


Matriz A:
[[ 0  3 -2]
 [-3  0  4]
 [ 2 -4  0]]
Transpuesta de A:
[[ 0 -3  2]
 [ 3  0 -4]
 [-2  4  0]]
Negativa de A:
[[ 0 -3  2]
 [ 3  0 -4]
 [-2  4  0]]
¿A es antisimétrica?
True


El rango de una matriz es un concepto fundamental en álgebra lineal que indica cuántas columnas (o filas) linealmente independientes tiene una matriz.

* Representa la dimensión del espacio generado por las columnas (columna espacio) o las filas (espacio fila).

* Es igual al número de pivotes no nulos en la forma escalonada de la matriz.

* Mide la "cantidad de información" o "grado de libertad" de la matriz.

$$
\begin{array}{ll}
\quad 1. \ \text{rango}(A) \leq \min(m, n) \\
\quad 2. \ \text{rango}(A) = \text{rango}(A^T) \\
\quad 3. \ \text{Si } \text{rango}(A) = n \ (\text{número de columnas}), \text{ las columnas son linealmente independientes.} \\
\quad 4. \ \text{Si } \text{rango}(A) = m \ (\text{número de filas}), \text{ las filas son linealmente independientes.}
\end{array}
$$

In [ ]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [2, 4, 6],
    [3, 6, 9]
])

print(np.linalg.matrix_rank(A))  # Resultado: 1, 
# np.linalg.matrix_rank calcula el rango de una matriz, el rango es el número máximo de columnas linealmente independientes en la matriz
# En este caso, todas las filas son múltiplos de la primera fila, por lo que el rango es 1.


1


solo hay una fila independiente.

In [99]:
# Definimos una matriz 4x4 arbitraria (puedes cambiarla si deseas otra)
A= np.array([
    [1, 2, 3, 4],
    [2, 4, 6, 8],
    [0, 1, 0, 1],
    [3, 6, 9, 12]
])

# Calcular el rango
rango_A = np.linalg.matrix_rank(A)
print("Rango de A:", rango_A)

Rango de A: 2


Esto significa que solo hay 2 filas (o columnas) linealmente independientes. Las demás son combinaciones lineales de estas.

Traza de la matriz

In [100]:
# Traza de la matriz (suma de la diagonal)
traza_A = np.trace(A)
print(traza_A)

17


## **OPERACIONES BASICAS DE MATRICES**

$$A=\begin{bmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31}& a_{32} & a_{33}
\end{bmatrix}
\\
\\
B=\begin{bmatrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31}& a_{32} & a_{33}
\end{bmatrix}
$$

In [110]:
import numpy as np
# Definir matrices de ejemplo 4x4
A = np.array([[2, 3, 1, 5],
              [4, 5, 6, 7],
              [8, 9, 10, 11],
              [12, 13, 14, 15]])

B = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

Suma de matrices

In [102]:
# Suma de matrices
suma_matrices = A + B
print(suma_matrices)


[[ 3  5  4  9]
 [ 9 11 13 15]
 [17 19 21 23]
 [25 27 29 31]]


Resta de matrices

In [103]:
# Resta de matrices
resta_matrices = A - B
print(resta_matrices)

[[ 1  1 -2  1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


Multiplicación de matrices

In [111]:
# Multiplicación de matrices
multiplicacion_matrices = A @ B  # También se puede usar np.dot(A, B)
print(multiplicacion_matrices)

[[ 91 102 113 124]
 [174 196 218 240]
 [286 324 362 400]
 [398 452 506 560]]


In [112]:
# Multiplicación de matrices
multi_matrices = np.dot(A, B)  # También se puede usar A @ B
print(multi_matrices)

[[ 91 102 113 124]
 [174 196 218 240]
 [286 324 362 400]
 [398 452 506 560]]


Multiplicación por un escalar

In [114]:
# Multiplicación por un escalar
escalar = 2
multiplicacion_escalar = escalar * A
print(A, "*", escalar, "=\n") 
print(multiplicacion_escalar)

[[ 2  3  1  5]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] * 2 =

[[ 4  6  2 10]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]]


Inversa de una matriz

$$
\text{Sean:} \\
A = \begin{bmatrix} 2 & 4 \\ 6 & 8 \end{bmatrix}, \quad
B = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} \\
\\
\text{Entonces, } "A \div B" \text{ se interpreta como:} \\
\\
A \cdot B^{-1}
$$

In [106]:
import numpy as np

A = np.array([[2, 4], [6, 8]])
B = np.array([[1, 2], [3, 4]])

# Calcular la inversa de B
B_inv = np.linalg.inv(B)

# Multiplicación A por B⁻¹
resultado = A @ B_inv

print(resultado)


[[2.00000000e+00 0.00000000e+00]
 [1.77635684e-15 2.00000000e+00]]


Traza de la matriz